backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "directors"
    label: "Blog"
    folder: "content/directors"
    create: true
    fields:
     - {label: "Firstname", name: "firstname", widget: "string"}
     - {label: "Name", name: "name", widget: "string"}
     - {label: "Years of live", name: "years of live", widget: "string"}
     - {label: "Location", name: "location", widget: "string"}
     - label: "Timeline"
       name: "timeline"
       widget: "list"
       fields:
        - label: Time
          name: time
          widget: string
          default: "01.01.1980"
        - label: Description
          name: description
          widget: string
     - label: "Gallery"
       name: "galleryImages"
       widget: "list"
       fields:
        - widget: image