backend:
  name: git-gateway
  branch: master

media_folder: src/images/uploads
public_folder: images/uploads

collections:
  - name: "director in English"
    label: "Director in English"
    folder: "src/content/directors/en"
    create: true
    identifier_field: id
    format: json
    extension: json
    filter: {field: "language", value: "en"}
    fields:
     - {label: "ID", name: id, widget: "string"}
     - {label: "Years of live", name: "years of live", widget: "string"}
     - {label: "Location", name: "location", widget: "string"}
     - label: "Gallery"
       name: "galleryImages"
       widget: "list"
       fields:
        - label: "Image"
          name: "image"
          widget: image
     - label: "English language"
       name: "english language"
       widget: "object"
       fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - label: "Timeline"
          name: "timeline"
          widget: "list"
          fields:
            - label: Time
              name: time
              widget: string
              default: "1980"
            - label: Description
              name: description
              widget: string
        - label: "Video"
          name: "video"
          widget: "string"
     - label: "Russian language"
       name: "russian language"
       widget: "object"
       fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - label: "Timeline"
          name: "timeline"
          widget: "list"
          fields:
            - label: Time
              name: time
              widget: string
              default: "1980"
            - label: Description
              name: description
              widget: string
        - label: "Video"
          name: "video"
          widget: "string"
     - label: "Belarusian language"
       name: "belarussian language"
       widget: "object"
       fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - label: "Timeline"
          name: "timeline"
          widget: "list"
          fields:
            - label: Time
              name: time
              widget: string
              default: "1980"
            - label: Description
              name: description
              widget: string
        - label: "Video"
          name: "video"
          widget: "string"