backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "director in English"
    label: "Director in English"
    folder: "src/content/directors/en"
    create: true
    identifier_field: id
    format: json
    extension: json
    filter: {field: "language", value: "en"}
    fields:
     - {label: "Language", name: "language", widget: "select", options: ["en", "by", "ru"]}
     - {label: "Name", name: "name", widget: "string"}
     - {label: "ID", name: id, widget: "string"}
     - {label: "Years of live", name: "years of live", widget: "string"}
     - {label: "Bio", name: "bio", widget: "markdown"}
     - {label: "Location", name: "location", widget: "string"}
     - label: "Timeline"
       name: "timeline"
       widget: "list"
       fields:
        - label: Time
          name: time
          widget: string
          default: "01.01.1980"
        - label: Description
          name: description
          widget: string
     - label: "Gallery"
       name: "galleryImages"
       widget: "list"
       fields:
        - label: "Image"
          name: "image"
          widget: image
     - label: "Video"
       name: "video"
       widget: "string"